name: trajectory_sim_insertion_scripted

image_shape: &image_shape [3, 240, 320]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    images:
      shape: *image_shape
      type: rgb
    qpos:
      shape: [14]
      type: low_dim
  next_keypose:
    shape: [14]
  action:
    shape: [14]

dataset:
  _target_: diffusion_policy.dataset.trajectory_aloha_dataset.TrajectoryAlohaDataset
  dataset_dir: data/aloha/datasets/
  shape_meta: *shape_meta
  seed: 42
  val_ratio: 0.2
  task: sim_insertion_scripted
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  use_cache: False
